root: true
extends:
  - 'eslint:recommended'
  - 'prettier'
  - 'plugin:vitest/recommended'
plugins:
  - 'simple-import-sort'
ignorePatterns:
  - dist/
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  simple-import-sort/imports: error
  simple-import-sort/exports: error
overrides:
  - files:
      - 'scripts/*'
    env:
      node: true
  - files:
      - '*.{ts,tsx}'
    extends:
      - 'plugin:@typescript-eslint/strict-type-checked'
      - 'plugin:@typescript-eslint/stylistic-type-checked'
    plugins:
      - '@typescript-eslint'
    parser: '@typescript-eslint/parser'
    parserOptions:
      project: true
    rules:
      '@typescript-eslint/consistent-type-definitions': 'off'
  - files:
      - '*.test.*'
    rules:
      vitest/no-focused-tests: error
      vitest/no-disabled-tests: error
      vitest/prefer-lowercase-title:
        - warn
        - ignoreTopLevelDescribe: true
