root: true
extends:
  - 'eslint:recommended'
  - 'prettier'
  - 'plugin:vitest/recommended'
ignorePatterns:
  - dist/
parserOptions:
  ecmaVersion: latest
  sourceType: module
overrides:
  - files:
      - '*.{ts,tsx}'
    extends:
      - 'plugin:@typescript-eslint/strict-type-checked'
      - 'plugin:@typescript-eslint/stylistic-type-checked'
    plugins:
      - '@typescript-eslint'
    parser: '@typescript-eslint/parser'
    parserOptions:
      project: true
    rules:
      '@typescript-eslint/consistent-type-definitions': 'off'
      '@typescript-eslint/no-misused-promises':
        - error
        - checksVoidReturn:
            attributes: false
  - files:
      - '*.test.*'
    rules:
      vitest/no-focused-tests: error
      vitest/no-disabled-tests: error
      vitest/prefer-lowercase-title:
        - warn
        - ignoreTopLevelDescribe: true
